### ISSUE TITLE
Linking to Backend

### ISSUE THREAD

**Issue by gideongrinberg** [manikandanraji/twitter-clone-frontend#3]
So this is probably a stupid question, but I'm trying to deploy this application so I can use it and make some changes. I've deployed my backend to Heroku by following the instructions in the backend repo. I've deployed my frontend to Vercel (formerly ZEIT Now). How do I link the two? Is that what the endpoint env vars are for? The Heroku URL just shows the GraphQL IDE, which I assume is correct.

Thanks in advance,
@gideon357

**Comment by manikandanraji** [comment]
yep, you need to use env vars for connecting the frontend and backend. By default, if you start the backend server on your local machine, it'll start listening for requests at port 7777. So, you should have .env file in your frontend repo with the following contents:

![carbon (1)](https://user-images.githubusercontent.com/34580944/100492311-d1af3f80-3150-11eb-94a0-fc2397525622.png)
