### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ytaijp** [manikandanraji/twitter-clone-frontend#4]
git clone https://github.com/manikandanraji/twitter-clone-frontend.git
cd twitter-clone-frontend

$ vim .env
REACT_APP_DEV=localhost:3000
REACT_APP_PROD=http://mydomain.com
REACT_APP_CLOUDINARY_URL=https://api.cloudinary.com/v1_1/<YOUR_CLOUD_NAME>/image/upload

sudo npm install 
sudo npm start

**Comment by manikandanraji** [comment]
make sure you start the backend dev server which by default will start at port 7777. 

then in your .env file, make the following change:

REACT_APP_DEV=http://localhost:7777

**Comment by ytaijp** [comment]
I completed your youtube video and backend, but

Failed to fetch

whats the problem..?

**Comment by ultra-pool** [comment]
`NetworkError when attempting to fetch resource`
This is error I get when trying to make a account.

**Comment by manikandanraji** [comment]
guys post your screenshot, it would be helpful to debug
